language: "python"
sudo: false

python:
   - "2.6"
   - "2.7"
   - "3.2"
   - "3.3"
   - "3.4"
   - "pypy"
   - "pypy3"

install:
   - pip install flake8
   - pip install pep257

before_script:
   - flake8 .
   - pep257 .

script:
   - python setup.py install
   - pikalang --version
