language: "python"

python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "3.6"
   - "pypy"
   - "pypy3"

install:
   - pip install pipenv
   - pipenv install --dev

before_script:
   - pipenv run black .

script:
   - python setup.py install
   - pikalang --version
   - pikalang test/hello-world.pokeball
