language: "python"

python:
   - "2.7"
   - "3.2"
   - "3.3"
   - "3.4"
   - "pypy"
   - "pypy3"

install:
   - pip install flake8
   - pip install pydocstyle

before_script:
   - flake8 .
   - pydocstyle .

script:
   - python setup.py install
   - pikalang --version
